name: CustomSayCommand
main: jp.ucchy.csc.CustomSayCommand
version: 0.0.1
author: ucchy
description: CustomSayCommand
commands:
  say:
    description: CustomSayCommand
    aliases: []
    usage: |
           /<command> kit - 全プレイヤーにキットを配布する
           /<command> clear - 全プレイヤーの持ち物を全て消去する
           /<command> teleport - マッチングしたプレイヤーを設定したテレポート先へテレポートする
           /<command> return - 全プレイヤーを観客席へテレポートする
           /<command> match - 全プレイヤーをマッチングする
    permission: customsay
    permission-message: パーミッション "<permission>" が無いため、実行できません。
permissions:
  customsay:
    description: CustomSayCommand
    default: op
