name: CustomSayCommand
main: jp.ucchy.csc.CustomSayCommand
version: 0.0.1
author: ucchy
description: CustomSayCommand
commands:
  say:
    description: CustomSayCommand
    aliases: []
    usage: /<command> (message) - サーバーにブロードキャストメッセージを表示する
    permission: customsay
    permission-message: パーミッション "<permission>" が無いため、実行できません。
permissions:
  customsay:
    description: CustomSayCommand
    default: op
